# Site settings
title: "Akshay's Resume"
description: "A resume of Akshay Gupta"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Akshay Gupta"
resume_title:                   "Embedded Sofware Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "akshay.j398p@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+91-7760083344"
resume_contact_address:         "398, Devi Nagar, Jaipur, India"

resume_header_contact_info:     "• +91-7760083344 • akshay.j398p@gmail.com"
display_header_contact_info:    "false"

# This is the executive summary. You should write a few brief, concise, and meaningful
# sentences about yourself from a professional context, and your immediate career goals.
# Make the length appropriate for your needs, but keep it brief and concise.
resume_header_intro: "<p> Over 7 years of experience in the combined areas of platform 
and bootloader development in automotive domain. Currently working on the hypervisor development
for the enterprise domain.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          false
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/akshayj398p"
  resume_twitter_url:           "https://twitter.com/akshayj398p"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/akshay-g-06b4b762"
  resume_instagram_url:         "https://www.instagram.com/akshay.j398p"
  resume_website_url:           "http://akshayj398p.com"
  resume_medium_url:           "https://medium.com/@akshay.j398p"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
